"""Deterministic data inspection script — NEVER generated by the LLM.

This is a fixed, trusted asset run inside the sandbox. It takes a file path,
loads it with pandas, and prints a structured JSON report to stdout.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd


def _detect_encoding(file_path: str) -> str:
    for enc in ("utf-8", "utf-8-sig", "latin-1", "gbk", "gb2312", "cp1252"):
        try:
            pd.read_csv(file_path, encoding=enc, nrows=1)
            return enc
        except (UnicodeDecodeError, UnicodeError):
            continue
    return "utf-8"


def _load_file(file_path: str) -> pd.DataFrame:
    path = Path(file_path)
    suffix = path.suffix.lower()
    if suffix == ".csv":
        encoding = _detect_encoding(file_path)
        return pd.read_csv(file_path, encoding=encoding)
    if suffix in (".xls", ".xlsx"):
        return pd.read_excel(file_path)
    raise ValueError(f"Unsupported file type: {suffix}")


def _safe_serialize(obj: object) -> object:
    """Convert numpy/pandas types to plain Python for JSON serialization."""
    import math

    import numpy as np

    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        val = float(obj)
        if math.isnan(val) or math.isinf(val):
            return None
        return val
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None
    if isinstance(obj, np.ndarray):
        return [_safe_serialize(x) for x in obj.tolist()]
    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()
    try:
        if pd.isna(obj):  # type: ignore[call-overload]
            return None
    except (TypeError, ValueError):
        pass
    return obj


def run(file_path: str) -> None:
    df = _load_file(file_path)

    # Basic shape
    rows, cols = df.shape

    # Column metadata
    columns: list[dict[str, object]] = []
    for col_name in df.columns:
        col_series = df[col_name]
        columns.append(
            {
                "name": str(col_name),
                "dtype": str(col_series.dtype),
                "null_count": int(col_series.isnull().sum()),
                "null_pct": round(float(col_series.isnull().sum() / len(col_series) * 100), 2),
                "unique_count": int(col_series.nunique()),
                "unique_pct": round(float(col_series.nunique() / len(col_series) * 100), 2),
            }
        )

    # Descriptive statistics (all columns, including non-numeric)
    describe = df.describe(include="all")
    stats: dict[str, dict[str, object]] = {}
    for col_name in describe.columns:
        col_stats: dict[str, object] = {}
        for stat_name in describe.index:
            val = describe.loc[stat_name, col_name]
            col_stats[str(stat_name)] = _safe_serialize(val)
        stats[str(col_name)] = col_stats

    # First 5 rows as list of records
    head_rows = df.head(5).to_dict(orient="records")
    head_rows_safe = [
        {str(k): _safe_serialize(v) for k, v in row.items()} for row in head_rows
    ]

    result = {
        "file_path": file_path,
        "shape": {"rows": rows, "cols": cols},
        "columns": columns,
        "statistics": stats,
        "head": head_rows_safe,
    }

    json.dump(result, sys.stdout, ensure_ascii=False, indent=2, default=str)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python inspection_script.py <file_path>", file=sys.stderr)
        sys.exit(1)
    run(sys.argv[1])
